# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-03 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='condition_of_book',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_pages',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='provider',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='year_of_edition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
