# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200103_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition_of_book',
            field=models.CharField(choices=[('like_new', 'Like new'), ('good', 'Good'), ('used', 'Used')], default='Like new', max_length=10),
        ),
    ]
