# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-13 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='rentrequest',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='rentrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='books',
            field=models.CharField(default='{{ item.product.id }}', max_length=30),
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rentrequest',
            name='number_of_books',
            field=models.CharField(default='{{ total }}', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentrequest',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
