# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-18 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20200313_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentrequest',
            old_name='full_name',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='rentrequest',
            name='number_of_books',
        ),
        migrations.AlterField(
            model_name='rentrequest',
            name='books',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
