# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-18 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200206_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='want_to_rent',
            field=models.BooleanField(default=False, verbose_name='I want to be able to rent books'),
        ),
    ]
