# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200218_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='have_paid',
            field=models.BooleanField(default=False, verbose_name='I have paid my deposite'),
        ),
    ]
