# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-17 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_have_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='want_to_rent',
            field=models.BooleanField(default=False, verbose_name='I want to be able to rent books*'),
        ),
    ]
