# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200208_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rentprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='saleprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
