# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-13 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200213_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rentprice',
            new_name='rentprice_per_week',
        ),
    ]
