# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200213_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition_of_book',
            field=models.CharField(choices=[('Like new', 'Like new'), ('Good', 'Good'), ('Used', 'Used')], default='Like new', max_length=10),
        ),
    ]
