# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200213_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rentprice_per_week',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='saleprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
