# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200214_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_for_rent',
            field=models.BooleanField(default=False, verbose_name='For rent?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='For sale?'),
        ),
    ]
