# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200214_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_for_rent',
            field=models.BooleanField(default=False, error_messages={'required': "Either 'For sale' or 'For rent' (or both) should be checked"}, verbose_name='For rent?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_for_sale',
            field=models.BooleanField(default=False, error_messages={'required': "Either 'For sale' or 'For rent' (or both) should be checked"}, verbose_name='For sale?'),
        ),
    ]
