# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200214_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
